# ================================================
# Kubernetes Manifest for the Minecraft Project
# Author   : Lumitek
# Date     : 2025-08-15
# Description:
#   This manifest contains the following configurations:
#   - The Argo CD Minecraft Server Application (Minecraft)
#   - Activated SyncPolicy
# ================================================
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "${GIT_REPO}"
    path: k8s
    targetRevision: main
  destination:
    server: "${KUBERNETES_SERVER}"
    namespace: "${NAMESPACE}"
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
---